// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dilgvrclnyvfboaqhyey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbGd2cmNsbnl2ZmJvYXFoeWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODk4MjYsImV4cCI6MjA2NDU2NTgyNn0.ygiRY5QeQXMd5hfGpUXnyQyFoQwmWS6VcotvSDGLuVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);